// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bCbugA_9guD0QzvBP8R7oaflNcHZwBo',
    appId: '1:612063604989:web:370c2ef6f07a6af8474e94',
    messagingSenderId: '612063604989',
    projectId: 'crashlens-233bf',
    authDomain: 'crashlens-233bf.firebaseapp.com',
    storageBucket: 'crashlens-233bf.firebasestorage.app',
    measurementId: 'G-GTW544EDTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHtGgdOqVluqIGweTbIpPJ3IA9O2F1Jw',
    appId: '1:612063604989:android:ea79a24493e85cd0474e94',
    messagingSenderId: '612063604989',
    projectId: 'crashlens-233bf',
    storageBucket: 'crashlens-233bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq84fxoTGh-JQTLDyTyEXB04jcMhzWuo',
    appId: '1:612063604989:ios:76b693dea259bff7474e94',
    messagingSenderId: '612063604989',
    projectId: 'crashlens-233bf',
    storageBucket: 'crashlens-233bf.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArq84fxoTGh-JQTLDyTyEXB04jcMhzWuo',
    appId: '1:612063604989:ios:76b693dea259bff7474e94',
    messagingSenderId: '612063604989',
    projectId: 'crashlens-233bf',
    storageBucket: 'crashlens-233bf.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1bCbugA_9guD0QzvBP8R7oaflNcHZwBo',
    appId: '1:612063604989:web:e2290631be608d2f474e94',
    messagingSenderId: '612063604989',
    projectId: 'crashlens-233bf',
    authDomain: 'crashlens-233bf.firebaseapp.com',
    storageBucket: 'crashlens-233bf.firebasestorage.app',
    measurementId: 'G-61R0V4P731',
  );
}
